### ISSUE TITLE
File argument must be of type string

### ISSUE THREAD

**Issue by Sobakaa** [jamesfalkner/microprofile-grafana#5]
When trying to run with an example JSON i get this error:
`[2021-10-19T11:46:41.622Z] TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at spawn (child_process.js:545:16)
    at processRequestRaw (/mnt/c/Users/dmko0914/microprofile-grafana/routes.js:53:19)
    at router.post (/mnt/c/Users/dmko0914/microprofile-grafana/routes.js:30:10)
    at Layer.handle [as handle_request] (/mnt/c/Users/dmko0914/microprofile-grafana/node_modules/express/lib/router/layer.js:95:5)
    at next (/mnt/c/Users/dmko0914/microprofile-grafana/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/mnt/c/Users/dmko0914/microprofile-grafana/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/mnt/c/Users/dmko0914/microprofile-grafana/node_modules/express/lib/router/layer.js:95:5)
    at /mnt/c/Users/dmko0914/microprofile-grafana/node_modules/express/lib/router/index.js:281:22`

Log below is from running using WSL, but running it on Ubuntu produces the same result.

**Comment by jamesfalkner** [comment]
Did you follow the prereqs and install _jsonnet_ and _grafonnet_ ? And also, did you set the environment variables `JSONNET_BIN`, `JSONNET_LIB`, `JSONNET_FILE` ?

If you simply cloned this repo and and tried to `npm install; npm start` then you will get that error.

**Comment by Sobakaa** [comment]
Thank you for a quick response. Yes ineed, it was due to a badly installed jsonnet. apt get jsonnet fixed it.
